name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout du code
      - name: Checkout code
        uses: actions/checkout@v3

      # Installer Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Installer les dépendances
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Exécuter les tests
      - name: Run tests
        run: python -m unittest discover tests

  build-docker-image:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      # Checkout du code
      - name: Checkout code
        uses: actions/checkout@v3

      # Se connecter à Docker Hub (optionnel, si vous voulez publier l'image)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # Construire l'image Docker
      - name: Build Docker image
        run: docker build -t hafezid/ci-cd-demo .

      # Publier l'image Docker (optionnel)
      - name: Push Docker image
        run: docker push hafezid/ci-cd-demo


  deploy-to-cloud:
    needs: build-docker-image
    runs-on: ubuntu-latest

